USE DATABASE &{{SNOWFLAKE_DATABASE}};
USE SCHEMA   &{{SNOWFLAKE_SCHEMA}};

-- =============================================================================
-- NEW TABLES: USERINFOPAYROLLMAPPING, LLDETAIL, USERINFOEMPSTATUS
-- =============================================================================

create or replace TABLE USERINFOPAYROLLMAPPING (
	DATABASEPHYSICALNAME     VARCHAR(16777216) NOT NULL,
	USERINFOPAYROLLMAPPINGID NUMBER(38,0)      NOT NULL,
	USERID                   NUMBER(38,0)      NOT NULL,
	PAYROLLCLIENTID          VARCHAR(36)       NOT NULL,
	PAYROLLEMPLOYEEID        NUMBER(38,0)      NOT NULL,
	STARTDATETIME            TIMESTAMP_NTZ(9)  NOT NULL,
	ENDDATETIME              TIMESTAMP_NTZ(9)  NOT NULL,
	MODIFIEDBY               NUMBER(38,0)      NOT NULL,
	MODIFIEDON               TIMESTAMP_NTZ(9)  NOT NULL,
	EMPLOYEESTATUS           NUMBER(38,0)      NOT NULL,
	WEID                     VARCHAR(100)      NOT NULL,
	WORKERVERSION            NUMBER(38,0)      NOT NULL,
	constraint PK_USERINFOPAYROLLMAPPING primary key (DATABASEPHYSICALNAME, USERINFOPAYROLLMAPPINGID)
);

--

create or replace TABLE LLDETAIL (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	LLDETAILID           NUMBER(38,0)      NOT NULL,
	LLID                 NUMBER(38,0)      NOT NULL,
	LLDETAILCODE         VARCHAR(300)      NOT NULL,
	LLDETAILNAME         VARCHAR(300)      NOT NULL,
	STARTDATE            TIMESTAMP_NTZ(9)  NOT NULL,
	ENDDATE              TIMESTAMP_NTZ(9)  NOT NULL,
	MODIFIEDBY           NUMBER(38,0)      NOT NULL,
	MODIFIEDON           TIMESTAMP_NTZ(9)  NOT NULL,
	ISDELETED            BOOLEAN           NOT NULL,
	EMPNOTESREQUIRED     BOOLEAN           NOT NULL,
	CREATEDON            TIMESTAMP_NTZ(9)  NOT NULL,
	CREATEDBY            NUMBER(38,0)      NOT NULL,
	PAYROLLUNIQUEID      NUMBER(38,0)      NOT NULL,
	ORIGINALCODE         VARCHAR(300)      NOT NULL,
	CASTARTDATE          TIMESTAMP_NTZ(9)  NOT NULL,
	CAENDDATE            TIMESTAMP_NTZ(9)  NOT NULL,
	PAYROLLCLIENTID      VARCHAR(36)       NOT NULL,
	COLORCODE            VARCHAR(7)        NOT NULL,
	constraint PK_LLDETAIL primary key (DATABASEPHYSICALNAME, LLDETAILID)
);

--

create or replace TABLE USERINFOEMPSTATUS (
	DATABASEPHYSICALNAME        VARCHAR(16777216) NOT NULL,
	USERINFOEMPSTATUSID         NUMBER(38,0)      NOT NULL,
	USERID                      NUMBER(38,0)      NOT NULL,
	EMPSTATUS                   NUMBER(38,0)      NOT NULL,
	STARTDATETIME               TIMESTAMP_NTZ(9)  NOT NULL,
	ENDDATETIME                 TIMESTAMP_NTZ(9)  NOT NULL,
	MODIFIEDBY                  NUMBER(38,0)      NOT NULL,
	MODIFIEDON                  TIMESTAMP_NTZ(9)  NOT NULL,
	DESCRIPTION                 VARCHAR(16777216) NOT NULL,
	RETURNTOWORKDATE            TIMESTAMP_NTZ(9)  NOT NULL,
	INACTIVEEMPDATAPROCESSDATE 	TIMESTAMP_NTZ(9)  NOT NULL,
	constraint PK_USERINFOEMPSTATUS primary key (DATABASEPHYSICALNAME, USERINFOEMPSTATUSID)
);

--

create or replace TABLE CUSTOMER (
	CUSTOMERID NUMBER(38,0) NOT NULL,
	CUSTOMERNAME VARCHAR(100) NOT NULL,
	DATABASECREATIONDATE TIMESTAMP_NTZ(9) NOT NULL,
	CUSTOMERALIAS VARCHAR(50) NOT NULL,
	CUSTOMERSTATUS NUMBER(38,0) NOT NULL,
	BRANDID NUMBER(38,0) NOT NULL,
	DATABASEPHYSICALNAME VARCHAR(50) NOT NULL,
	DATABASESERVER VARCHAR(50) NOT NULL,
	SUPPORTEMAILADDRESS VARCHAR(100) NOT NULL,
	IVRALIAS NUMBER(38,0) NOT NULL,
	ACTIVEEMPLOYEES NUMBER(38,0) NOT NULL,
	EMAILSERVER VARCHAR(100) NOT NULL,
	EMAILPORT NUMBER(38,0) NOT NULL,
	EMAILSSLENABLED BOOLEAN NOT NULL,
	EMAILACCOUNT VARCHAR(100) NOT NULL,
	EMAILUSERNAME VARCHAR(100) NOT NULL,
	EMAILPASSWORD VARCHAR(255) NOT NULL,
	EMAILDOMAIN VARCHAR(255) NOT NULL,
	EMAILSETTINGSOVERRIDE BOOLEAN NOT NULL,
	QUEUEDELAYUNTIL TIMESTAMP_NTZ(9) NOT NULL,
	MODIFIEDBY NUMBER(38,0) NOT NULL,
	MODIFIEDON TIMESTAMP_NTZ(9) NOT NULL,
	WIRELESSENABLED BOOLEAN NOT NULL,
	FINGERPRINTENABLED BOOLEAN NOT NULL,
	CUSTOMERIDEXTERNAL VARCHAR(255) NOT NULL,
	WSTRACEENABLED BOOLEAN NOT NULL,
	WSTIMESTARTED TIMESTAMP_NTZ(9) NOT NULL,
	WSSTARTEDBY NUMBER(38,0) NOT NULL,
	TELEPUNCHALIAS NUMBER(38,0) NOT NULL,
	BISCLIENTID VARCHAR(50) NOT NULL,
	CUSTOMERLASTACTIVATEDBY NUMBER(38,0) NOT NULL,
	CUSTOMERLASTACTIVATEDON TIMESTAMP_NTZ(9) NOT NULL,
	CUSTOMERLASTDEACTIVATEDBY NUMBER(38,0) NOT NULL,
	CUSTOMERLASTDEACTIVATEDON TIMESTAMP_NTZ(9) NOT NULL,
	ISPROXY BOOLEAN NOT NULL,
	MIGWORKFLOW NUMBER(38,0) NOT NULL,
	ISESSENTIALS BOOLEAN NOT NULL,
	ISC2C BOOLEAN NOT NULL,
	DONOTDELETE BOOLEAN NOT NULL,
	ROLLUPMULTIFEINSHAREDEMPLOYEE NUMBER(5,0) NOT NULL,
	CUSTOMERCREATIONSTATUSTYPE NUMBER(38,0) NOT NULL,
	ENABLEAUTOCLOSINGTIMECARD BOOLEAN NOT NULL,
	ENTERPRISECAIDBILL VARCHAR(36) NOT NULL,
	CEIDBILL VARCHAR(36) NOT NULL,
	PAYROLLCLIENTIDBILL VARCHAR(36) NOT NULL,
	CLIENTTYPE NUMBER(38,0) NOT NULL,
	constraint AK_CUSTOMER_DATABASEPHYSICALNAME unique (DATABASEPHYSICALNAME),
	constraint PK_CUSTOMER primary key (CUSTOMERID)
);

--

create or replace TABLE ENTERPRISECUSTOMER (
	ENTERPRISECUSTOMERID NUMBER(38,0) NOT NULL,
	CUSTOMERID NUMBER(38,0) NOT NULL,
	PNGSSOCAID VARCHAR(36) NOT NULL,
	CEID VARCHAR(36) NOT NULL,
	PAYROLLCLIENTID VARCHAR(36) NOT NULL,
	MODIFIEDBY NUMBER(38,0) NOT NULL,
	MODIFIEDON TIMESTAMP_NTZ(9) NOT NULL,
	STRATUSTIMECAID VARCHAR(20) NOT NULL,
	LEGALCLIENTNAME VARCHAR(80) NOT NULL,
	CEIDSTATUS VARCHAR(10) NOT NULL,
	CEIDSTATUSDATE TIMESTAMP_NTZ(9) NOT NULL,
	MODIFIEDCHANGEREASON VARCHAR(100) NOT NULL,
	CEIDSUPERSEDEDBY VARCHAR(20) NOT NULL,
	CACAID VARCHAR(20) NOT NULL,
	HRISCAID VARCHAR(20) NOT NULL,
	BISCLIENTID VARCHAR(50) NOT NULL,
	USEDCLIENTMAINT BOOLEAN NOT NULL,
	constraint PK_ENTERPRISECUSTOMER primary key (ENTERPRISECUSTOMERID)
);

--

create or replace TABLE PAYTYPE (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	ID NUMBER(38,0) NOT NULL,
	PAYTYPEID NUMBER(38,0) NOT NULL,
	STARTDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	ENDDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	ISDELETED BOOLEAN NOT NULL,
	PAYTYPENAME VARCHAR(50) NOT NULL,
	PAYTYPECODE VARCHAR(50) NOT NULL,
	COUNTTOWARDSHOLIDAYMIN BOOLEAN NOT NULL,
	OVERRIDESABSENCE BOOLEAN NOT NULL,
	ISWORKTYPE BOOLEAN NOT NULL,
	APPLYTOOVERTIME BOOLEAN NOT NULL,
	INCLUDEINBLENDEDRATE BOOLEAN NOT NULL,
	APPLYTOTIMEOFF BOOLEAN NOT NULL,
	CANBEOVERTIME BOOLEAN NOT NULL,
	DEFAULTPAYLEVELRATETYPE NUMBER(38,0) NOT NULL,
	ISOVERTIMETYPE BOOLEAN NOT NULL,
	OVERTIMEFACTOR NUMBER(18,2) NOT NULL,
	COLORCODE VARCHAR(1) NOT NULL,
	MODIFIEDBY NUMBER(38,0) NOT NULL,
	MODIFIEDON TIMESTAMP_NTZ(9) NOT NULL,
	ALLOWSHIFTDIFF BOOLEAN NOT NULL,
	DEDUCTFROMPAYTYPE BOOLEAN NOT NULL,
	DEDUCTFROMPAYTYPEID NUMBER(38,0) NOT NULL,
	ISDURATIONONLY BOOLEAN NOT NULL,
	ISLLREQUIRED BOOLEAN NOT NULL,
	ISFMLATYPE BOOLEAN NOT NULL,
	PAYATWEIGHTEDRATE BOOLEAN NOT NULL
);

--

create or replace TABLE SCHEDULE (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	SCHEDULEID NUMBER(38,0) NOT NULL,
	USERID NUMBER(38,0) NOT NULL,
	PAYTYPEID NUMBER(38,0) NOT NULL,
	STARTDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	ENDDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	LLDETAILID1 NUMBER(38,0) NOT NULL,
	LLDETAILID2 NUMBER(38,0) NOT NULL,
	LLDETAILID3 NUMBER(38,0) NOT NULL,
	LLDETAILID4 NUMBER(38,0) NOT NULL,
	LLDETAILID5 NUMBER(38,0) NOT NULL,
	LLDETAILID6 NUMBER(38,0) NOT NULL,
	LLDETAILID7 NUMBER(38,0) NOT NULL,
	LLDETAILID8 NUMBER(38,0) NOT NULL,
	LLDETAILID9 NUMBER(38,0) NOT NULL,
	LLDETAILID10 NUMBER(38,0) NOT NULL,
	LLDETAILID11 NUMBER(38,0) NOT NULL,
	LLDETAILID12 NUMBER(38,0) NOT NULL,
	LLDETAILID13 NUMBER(38,0) NOT NULL,
	LLDETAILID14 NUMBER(38,0) NOT NULL,
	LLDETAILID15 NUMBER(38,0) NOT NULL,
	ISAUTOGENERATED BOOLEAN NOT NULL,
	MODIFIEDBY NUMBER(38,0) NOT NULL,
	MODIFIEDON TIMESTAMP_NTZ(9) NOT NULL,
	ADVSCHEDULECAPACITYDETAILID NUMBER(38,0) NOT NULL,
	NOTE VARCHAR(16777216) NOT NULL,
	STARTDATETIMEUTC TIMESTAMP_NTZ(9) NOT NULL,
	ENDDATETIMEUTC TIMESTAMP_NTZ(9) NOT NULL,
	CALENDAREVENTID VARCHAR(16777216) NOT NULL,
	ISCALENDARSYNC BOOLEAN NOT NULL,
	SCHEDULEGENERATEDSOURCE NUMBER(38,0) NOT NULL,
	USERHASBEENNOTIFIED BOOLEAN NOT NULL,
	constraint PK_SCHEDULE primary key (DATABASEPHYSICALNAME, SCHEDULEID)
);

--

create or replace TABLE TIMEOFFDATA (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	TIMEOFFDATAID NUMBER(38,0) NOT NULL,
	USERID NUMBER(38,0) NOT NULL,
	PAYTYPEID NUMBER(38,0) NOT NULL,
	ACCRUEDSECS NUMBER(38,0) NOT NULL,
	GRANTEDSECS NUMBER(38,0) NOT NULL,
	MANSECS NUMBER(38,0) NOT NULL,
	USEDSECS NUMBER(38,0) NOT NULL,
	AVAILABLESECS NUMBER(38,0) NOT NULL,
	APPLYTODATETIME TIMESTAMP_NTZ(9) NOT NULL,
	ADJUSTMENTUSERID NUMBER(38,0) NOT NULL,
	ISSYSTEMGENERATED BOOLEAN NOT NULL,
	NOTES VARCHAR(16777216) NOT NULL,
	TIMESLICEPREID NUMBER(38,0) NOT NULL,
	CREATIONDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	MODIFIEDBY NUMBER(38,0) NOT NULL,
	MODIFIEDON TIMESTAMP_NTZ(9) NOT NULL,
	MAKEUPSECS NUMBER(38,0) NOT NULL,
	ANCHORPOINT BOOLEAN NOT NULL,
	ROLLOVERSECS NUMBER(38,0) NOT NULL,
	FORFEITEDSECS NUMBER(38,0) NOT NULL,
	TRANSFERINID NUMBER(38,0) NOT NULL,
	TRANSFERINSECS NUMBER(38,0) NOT NULL,
	TRANSFEROUTID NUMBER(38,0) NOT NULL,
	TRANSFEROUTSECS NUMBER(38,0) NOT NULL,
	TOTALACCRUEDSECS NUMBER(38,0) NOT NULL,
	MANTYPE NUMBER(38,0) NOT NULL,
	ISROLLOVER BOOLEAN NOT NULL,
	PROCESSINDEX NUMBER(38,0) NOT NULL,
	DELAYEDGRANTSECS NUMBER(38,0) NOT NULL,
	SECONDSWORKEDSTORE NUMBER(38,0) NOT NULL,
	EXPIRESDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	ROLLOVERTRANSFERINID NUMBER(38,0) NOT NULL,
	ROLLOVERTRANSFERINSECS NUMBER(38,0) NOT NULL,
	ROLLOVERTRANSFEROUTID NUMBER(38,0) NOT NULL,
	ROLLOVERTRANSFEROUTSECS NUMBER(38,0) NOT NULL,
	LASTPROCESSEDEVENTID VARCHAR(16777216),
	LASTPROCESSEDEVENTDATETIME TIMESTAMP_NTZ(9)
);

--

create or replace TABLE TIMEOFFREQUEST (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	TIMEOFFREQUESTID NUMBER(38,0) NOT NULL,
	USERID NUMBER(38,0) NOT NULL,
	PAYTYPEID NUMBER(38,0) NOT NULL,
	TIMEOFFPOLICYDETAILID NUMBER(38,0) NOT NULL,
	DATETIMESUBMITTED TIMESTAMP_NTZ(9) NOT NULL,
	STARTDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	ENDDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	INCLUDEWEEKENDS BOOLEAN NOT NULL,
	DURATIONPERDAYSECS NUMBER(38,0) NOT NULL,
	STATUSTYPE NUMBER(38,0) NOT NULL,
	STATUSCHANGEDON TIMESTAMP_NTZ(9) NOT NULL,
	EMPNOTES VARCHAR(500) NOT NULL,
	ISBUYOUTREQUEST BOOLEAN NOT NULL,
	BUYOUTSECS NUMBER(38,0) NOT NULL,
	BUYOUTADJUSTMENTID NUMBER(38,0) NOT NULL,
	PAYADJUSTMENTDATAID NUMBER(38,0) NOT NULL,
	constraint PK_TIMEOFFREQUEST primary key (DATABASEPHYSICALNAME, TIMEOFFREQUESTID)
);

--

create or replace TABLE TIMEOFFREQUESTDETAIL (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	TIMEOFFREQUESTDETAILID NUMBER(38,0) NOT NULL,
	TIMEOFFREQUESTID NUMBER(38,0) NOT NULL,
	STARTDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	ENDDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	STATUSTYPE NUMBER(38,0) NOT NULL,
	ISDELETED BOOLEAN NOT NULL,
	STATUSCHANGEDBY NUMBER(38,0) NOT NULL,
	STATUSCHANGEDON TIMESTAMP_NTZ(9) NOT NULL,
	MGRNOTES VARCHAR(500) NOT NULL,
	TIMESLICEPREID NUMBER(38,0) NOT NULL,
	AUTORESETQUALIFYBYHOURSWORKED BOOLEAN NOT NULL,
	ISCALENDARSYNC BOOLEAN NOT NULL,
	CALENDAREVENTID VARCHAR(16777216) NOT NULL,
	constraint PK_TIMEOFFREQUESTDETAIL primary key (DATABASEPHYSICALNAME, TIMEOFFREQUESTDETAILID)
);

--

create or replace TABLE TIMESLICEPOST (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	TIMESLICEPOSTID NUMBER(38,0) NOT NULL,
	USERID NUMBER(38,0) NOT NULL,
	PAYTYPEID NUMBER(38,0) NOT NULL,
	TIMESLICEPREIDIN NUMBER(38,0) NOT NULL,
	TIMESLICEPREIDOUT NUMBER(38,0) NOT NULL,
	ACTUALDATETIMEIN TIMESTAMP_NTZ(9) NOT NULL,
	ACTUALDATETIMEOUT TIMESTAMP_NTZ(9) NOT NULL,
	ROUNDEDDATETIMEIN TIMESTAMP_NTZ(9) NOT NULL,
	ROUNDEDDATETIMEOUT TIMESTAMP_NTZ(9) NOT NULL,
	UTCDATETIMEIN TIMESTAMP_NTZ(9) NOT NULL,
	UTCDATETIMEOUT TIMESTAMP_NTZ(9) NOT NULL,
	TOTALPAIDDURATIONSECS NUMBER(38,0) NOT NULL,
	REGDURATIONSECS NUMBER(38,0) NOT NULL,
	OTDURATIONSECS NUMBER(38,0) NOT NULL,
	UNPAIDDURATIONSECS NUMBER(38,0) NOT NULL,
	MGRAPPROVEDIN BOOLEAN NOT NULL,
	MGRAPPROVEDOUT BOOLEAN NOT NULL,
	MGRNOTEIN VARCHAR(16777216) NOT NULL,
	MGRNOTEOUT VARCHAR(16777216) NOT NULL,
	EMPAPPROVEDIN BOOLEAN NOT NULL,
	EMPAPPROVEDOUT BOOLEAN NOT NULL,
	EMPNOTEIN VARCHAR(16777216) NOT NULL,
	EMPNOTEOUT VARCHAR(16777216) NOT NULL,
	TIMESHEETSUBMISSIONIN BOOLEAN NOT NULL,
	TIMESHEETSUBMISSIONOUT BOOLEAN NOT NULL,
	PAYRATE NUMBER(19,4) NOT NULL,
	CHARGERATE NUMBER(19,4) NOT NULL,
	TOTALEARNINGS NUMBER(19,4) NOT NULL,
	MISSINGPUNCHTYPEIN NUMBER(38,0) NOT NULL,
	MISSINGPUNCHTYPEOUT NUMBER(38,0) NOT NULL,
	ISMODIFIEDIN BOOLEAN NOT NULL,
	ISMODIFIEDOUT BOOLEAN NOT NULL,
	SCHEDULEID NUMBER(38,0) NOT NULL,
	SCHEDULEDETAILID NUMBER(38,0) NOT NULL,
	APPLYTODATE TIMESTAMP_NTZ(9) NOT NULL,
	CLOSEDTYPE NUMBER(38,0) NOT NULL,
	TIMESLICEGROUPID VARCHAR(50) NOT NULL,
	LLDETAILID1 NUMBER(38,0) NOT NULL,
	LLDETAILID2 NUMBER(38,0) NOT NULL,
	LLDETAILID3 NUMBER(38,0) NOT NULL,
	LLDETAILID4 NUMBER(38,0) NOT NULL,
	LLDETAILID5 NUMBER(38,0) NOT NULL,
	LLDETAILID6 NUMBER(38,0) NOT NULL,
	LLDETAILID7 NUMBER(38,0) NOT NULL,
	LLDETAILID8 NUMBER(38,0) NOT NULL,
	LLDETAILID9 NUMBER(38,0) NOT NULL,
	LLDETAILID10 NUMBER(38,0) NOT NULL,
	LLDETAILID11 NUMBER(38,0) NOT NULL,
	LLDETAILID12 NUMBER(38,0) NOT NULL,
	LLDETAILID13 NUMBER(38,0) NOT NULL,
	LLDETAILID14 NUMBER(38,0) NOT NULL,
	LLDETAILID15 NUMBER(38,0) NOT NULL,
	HASHVALUE VARCHAR(900) NOT NULL,
	TRANSACTIONTYPEIN NUMBER(38,0) NOT NULL,
	TRANSACTIONTYPEOUT NUMBER(38,0) NOT NULL,
	TRANSACTIONSOURCEIN NUMBER(38,0) NOT NULL,
	TRANSACTIONSOURCEOUT NUMBER(38,0) NOT NULL,
	APPLYTOOVERTIME BOOLEAN NOT NULL,
	PAYLEVELRATETYPE NUMBER(38,0) NOT NULL,
	HASMODIFIER BOOLEAN NOT NULL,
	ISCANCELED BOOLEAN NOT NULL,
	COUNTTOWARDSHOLIDAYMIN BOOLEAN NOT NULL,
	HASSHIFTDIFF BOOLEAN NOT NULL,
	ISMEALPREMIUM BOOLEAN NOT NULL,
	MODIFIEDBY NUMBER(38,0) NOT NULL,
	MODIFIEDON TIMESTAMP_NTZ(9) NOT NULL,
	ADMINAPPROVEDIN BOOLEAN NOT NULL,
	ADMINAPPROVEDOUT BOOLEAN NOT NULL,
	MGR2APPROVEDIN BOOLEAN NOT NULL,
	MGR2APPROVEDOUT BOOLEAN NOT NULL,
	LONGITUDEIN NUMBER(18,4) NOT NULL,
	LONGITUDEOUT NUMBER(18,4) NOT NULL,
	LATITUDEIN NUMBER(18,4) NOT NULL,
	LATITUDEOUT NUMBER(18,4) NOT NULL,
	ISCOMPTIME BOOLEAN NOT NULL,
	COMPTIMEREQUESTID NUMBER(38,0) NOT NULL,
	COMPTIMEOTCONVERTEDSECS NUMBER(38,0) NOT NULL,
	MGRAPPROVEDBYIN NUMBER(38,0) NOT NULL,
	MGRAPPROVEDBYOUT NUMBER(38,0) NOT NULL,
	MGR2APPROVEDBYIN NUMBER(38,0) NOT NULL,
	MGR2APPROVEDBYOUT NUMBER(38,0) NOT NULL,
	ADMINAPPROVEDBYIN NUMBER(38,0) NOT NULL,
	ADMINAPPROVEDBYOUT NUMBER(38,0) NOT NULL,
	ISFORECAST BOOLEAN NOT NULL,
	ISRECONCILE BOOLEAN NOT NULL,
	ISSWIPEANDGOIN BOOLEAN NOT NULL,
	ISSWIPEANDGOOUT BOOLEAN NOT NULL,
	POPULATEDFROMSCHEDULEIN BOOLEAN NOT NULL,
	POPULATEDFROMSCHEDULEOUT BOOLEAN NOT NULL,
	ISCALLBACK BOOLEAN NOT NULL,
	ACCURACYIN NUMBER(18,4) NOT NULL,
	ACCURACYOUT NUMBER(18,4) NOT NULL,
	ISBREAKPREMIUM BOOLEAN NOT NULL,
	ADDITIONALPREMIUMTYPE NUMBER(38,0) NOT NULL
);

--

create or replace TABLE TIMESLICEPOSTEXCEPTIONDETAIL (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	TIMESLICEPOSTEXCEPTIONDETAILID NUMBER(38,0) NOT NULL,
	USERID NUMBER(38,0) NOT NULL,
	TIMESLICEPOSTID NUMBER(38,0) NOT NULL,
	TIMESLICEPREID NUMBER(38,0) NOT NULL,
	SCHEDULEID NUMBER(38,0) NOT NULL,
	DATETIME TIMESTAMP_NTZ(9) NOT NULL,
	EXCEPTIONPOLICYRULEID NUMBER(38,0) NOT NULL,
	EXCEPTIONTYPE NUMBER(38,0) NOT NULL,
	TRANSACTIONTYPE NUMBER(38,0) NOT NULL,
	EXCEPTIONPARAMETERSECS NUMBER(38,0) NOT NULL,
	HASHVALUE VARCHAR(900) NOT NULL,
	ISACKNOWLEDGED BOOLEAN NOT NULL,
	MODIFIEDBY NUMBER(38,0) NOT NULL,
	MODIFIEDON TIMESTAMP_NTZ(9) NOT NULL,
	MGRNOTE VARCHAR(16777216) NOT NULL,
	ACKNOWLEDGEDBY NUMBER(38,0) NOT NULL,
	constraint PK_TIMESLICEPOSTEXCEPTIONDETAIL primary key (DATABASEPHYSICALNAME, TIMESLICEPOSTEXCEPTIONDETAILID)
);

--

create or replace TABLE TIMESLICEPOSTSHIFTDIFFDETAIL (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	TIMESLICEPOSTSHIFTDIFFDETAILID NUMBER(38,0) NOT NULL,
	TIMESLICEPOSTID NUMBER(38,0) NOT NULL,
	STARTDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	ENDDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	STARTDATETIMEUTC TIMESTAMP_NTZ(9) NOT NULL,
	ENDDATETIMEUTC TIMESTAMP_NTZ(9) NOT NULL,
	DURATION NUMBER(38,0) NOT NULL,
	SHIFTDIFFDETAILID NUMBER(38,0) NOT NULL,
	SHIFTDIFFCODE VARCHAR(200) NOT NULL,
	SHIFTDIFFFACTOR NUMBER(18,2) NOT NULL,
	SHIFTDIFFADDITIONAL NUMBER(19,4) NOT NULL,
	FINALPAYRATE NUMBER(19,4) NOT NULL,
	HASHVALUE VARCHAR(900) NOT NULL,
	MODIFIEDBY NUMBER(38,0) NOT NULL,
	MODIFIEDON TIMESTAMP_NTZ(9) NOT NULL,
	SHIFTDIFFAFTEROVERTIME BOOLEAN NOT NULL,
	constraint PK_TIMESLICEPOSTSHIFTDIFFDETAIL primary key (DATABASEPHYSICALNAME, TIMESLICEPOSTSHIFTDIFFDETAILID)
);

--

create or replace TABLE USERINFO (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	USERID               NUMBER(38,0)      NOT NULL,
	EMPIDENTIFIER        VARCHAR(50)       NOT NULL,
	MODIFIEDON           TIMESTAMP_NTZ(9)  NOT NULL,
	STARTDATE            TIMESTAMP_NTZ(9)  NOT NULL,
	CLIENTID             VARCHAR(50)       NOT NULL,
	PAYROLLEMPLOYEEID    NUMBER(38,0)      NOT NULL,
	WEID                 VARCHAR(20)       NOT NULL,
	PEID                 VARCHAR(20)       NOT NULL,
	PNGSSOUSERGUID       VARCHAR(20)       NOT NULL,
	ISSHAREDWORKER       BOOLEAN           NOT NULL,
	PNGUSERNAME          VARCHAR(25)       NOT NULL,
	constraint PK_USERINFO primary key (DATABASEPHYSICALNAME, USERID)
);

--

create or replace TABLE USERINFOISSALARY (
	DATABASEPHYSICALNAME VARCHAR(16777216) NOT NULL,
	USERINFOISSALARYID NUMBER(38,0) NOT NULL,
	USERID NUMBER(38,0) NOT NULL,
	ISSALARY BOOLEAN NOT NULL,
	STARTDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	ENDDATETIME TIMESTAMP_NTZ(9) NOT NULL,
	MODIFIEDBY NUMBER(38,0) NOT NULL,
	MODIFIEDON TIMESTAMP_NTZ(9) NOT NULL
);

--
