USE DATABASE &{{SNOWFLAKE_DATABASE}};
USE SCHEMA   &{{SNOWFLAKE_SCHEMA}};

CREATE OR REPLACE PROCEDURE DELTA_LOAD_SCHEDULE(
    STAGE_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var total_inserts     = 0;
    var total_updates     = 0;
    var total_deletes     = 0;
    var files_processed   = 0;
    var total_rows_copied = 0;

    try {
        // Step 1: Collect all manifest files for this table into a list + metadata map.
        var get_files_query = `
            SELECT
                SUBSTRING(full_file_path, POSITION(''/LandingZone/'' IN full_file_path)) AS relative_path,
                client_id, table_id, filename, full_file_path, last_modified
            FROM STAGE_TAA_DELTA_MANIFEST
            WHERE table_id = ''f4830a1d-ae29-8044-7c71-6bd4b5779b70''
            ORDER BY last_modified ASC
        `;
        var file_results  = snowflake.createStatement({sqlText: get_files_query}).execute();
        var file_list     = [];
        var file_metadata = {};

        while (file_results.next()) {
            var relative_path  = file_results.getColumnValue(1);
            var client_id      = file_results.getColumnValue(2);
            var table_id       = file_results.getColumnValue(3);
            var filename       = file_results.getColumnValue(4);
            var full_file_path = file_results.getColumnValue(5);

            file_list.push("''" + relative_path + "''");
            file_metadata[relative_path] = {
                client_id:      client_id,
                table_id:       table_id,
                filename:       filename,
                full_file_path: full_file_path
            };
        }
        if (file_list.length === 0) { return "No delta files found for SCHEDULE."; }

        // Step 2: TRUNCATE staging once before all batches.
        snowflake.createStatement({sqlText: "TRUNCATE TABLE STG_DELTA_SCHEDULE;"}).execute();

        // Step 3: COPY all files into staging in batches of 1000.
        //         Write per-file audit rows from each COPY result set.
        var batch_size  = 1000;
        var batch_count = Math.ceil(file_list.length / batch_size);

        for (var batch_num = 0; batch_num < batch_count; batch_num++) {
            var start        = batch_num * batch_size;
            var end          = Math.min(start + batch_size, file_list.length);
            var files_clause = file_list.slice(start, end).join(", ");

            var copy_sql = `
                COPY INTO STG_DELTA_SCHEDULE (
                    CHANGE_TYPE, LSN, DATABASEPHYSICALNAME, SCHEDULEID, USERID, PAYTYPEID,
                    STARTDATETIME, ENDDATETIME,
                    LLDETAILID1, LLDETAILID2, LLDETAILID3, LLDETAILID4, LLDETAILID5,
                    LLDETAILID6, LLDETAILID7, LLDETAILID8, LLDETAILID9, LLDETAILID10,
                    LLDETAILID11, LLDETAILID12, LLDETAILID13, LLDETAILID14, LLDETAILID15,
                    ISAUTOGENERATED, MODIFIEDBY, MODIFIEDON, ADVSCHEDULECAPACITYDETAILID,
                    NOTE, STARTDATETIMEUTC, ENDDATETIMEUTC, CALENDAREVENTID,
                    ISCALENDARSYNC, SCHEDULEGENERATEDSOURCE, USERHASBEENNOTIFIED
                )
                FROM (
                    SELECT
                        $3::NUMBER(38,0),
                        TO_NUMBER(SUBSTR($1::TEXT, 3), ''XXXXXXXXXXXXXXXXXXXXXXXX''),
                        REGEXP_SUBSTR(METADATA$FILENAME::STRING, ''/([^/]+)/Tables/'', 1, 1, ''e''),
                        $5::NUMBER(38,0), $6::NUMBER(38,0), $7::NUMBER(38,0),
                        TRY_TO_TIMESTAMP_NTZ($8), TRY_TO_TIMESTAMP_NTZ($9),
                        $10::NUMBER(38,0), $11::NUMBER(38,0), $12::NUMBER(38,0),
                        $13::NUMBER(38,0), $14::NUMBER(38,0), $15::NUMBER(38,0),
                        $16::NUMBER(38,0), $17::NUMBER(38,0), $18::NUMBER(38,0),
                        $19::NUMBER(38,0), $20::NUMBER(38,0), $21::NUMBER(38,0),
                        $22::NUMBER(38,0), $23::NUMBER(38,0), $24::NUMBER(38,0),
                        $25::BOOLEAN, $26::NUMBER(38,0), TRY_TO_TIMESTAMP_NTZ($27), $28::NUMBER(38,0),
                        $29::TEXT, TRY_TO_TIMESTAMP_NTZ($30), TRY_TO_TIMESTAMP_NTZ($31), $32::TEXT,
                        $33::BOOLEAN, $34::NUMBER(38,0), $35::BOOLEAN
                    FROM @` + STAGE_NAME + ` (FILE_FORMAT => ''FF_TAA_ONELAKE_CSV'')
                )
                FILES = (` + files_clause + `)
                ON_ERROR = CONTINUE FORCE = TRUE
            `;
            var copy_result = snowflake.createStatement({sqlText: copy_sql}).execute();

            while (copy_result.next()) {
                var file_name   = copy_result.getColumnValue(1);
                var status      = copy_result.getColumnValue(2);
                var rows_loaded = copy_result.getColumnValue(4);
                var first_error = copy_result.getColumnValue(7);

                var rel_path    = file_name.indexOf("/LandingZone/") > -1
                    ? file_name.substring(file_name.indexOf("/LandingZone/")) : file_name;
                var meta        = file_metadata[rel_path] || {};
                var load_status = (status === "LOADED") ? "SUCCESS" : "FAILED";

                var safe_filename  = (meta.filename       || file_name).replace(/''/g, "''''");
                var safe_full_path = (meta.full_file_path || file_name).replace(/''/g, "''''");
                var safe_client_id = (meta.client_id      || "UNKNOWN");
                var safe_table_id  = (meta.table_id       || "UNKNOWN");
                var safe_error     = first_error ? first_error.replace(/''/g, "''''") : null;

                snowflake.createStatement({ sqlText: `
                    INSERT INTO INGEST_TAA_FILE_AUDIT
                        (file_name, client_id, table_id, rows_loaded, batch_number,
                         load_status, error_message, full_stage_path)
                    VALUES (
                        ''` + safe_filename  + `'', ''` + safe_client_id + `'',
                        ''` + safe_table_id  + `'', ` + rows_loaded + `,
                        `  + (batch_num + 1) + `, ''` + load_status + `'',
                        `  + (safe_error ? "''" + safe_error + "''" : "NULL") + `,
                        ''` + safe_full_path + `''
                    )
                `}).execute();

                total_rows_copied += rows_loaded;
                files_processed++;
            }
        }

        // Step 4: ONE MERGE across all staged rows. LSN dedup guarantees last-value-wins.
        var merge_sql = `
            MERGE INTO SCHEDULE tgt
            USING (
                SELECT * FROM STG_DELTA_SCHEDULE WHERE CHANGE_TYPE IN (1,2,4)
                QUALIFY ROW_NUMBER() OVER (
                    PARTITION BY DATABASEPHYSICALNAME, SCHEDULEID
                    ORDER BY LSN DESC NULLS LAST
                ) = 1
            ) src
            ON  tgt.DATABASEPHYSICALNAME = src.DATABASEPHYSICALNAME
            AND tgt.SCHEDULEID           = src.SCHEDULEID
            WHEN MATCHED AND src.CHANGE_TYPE = 1 THEN DELETE
            WHEN MATCHED AND src.CHANGE_TYPE = 4 THEN UPDATE SET
                tgt.USERID                      = src.USERID,
                tgt.PAYTYPEID                   = src.PAYTYPEID,
                tgt.STARTDATETIME               = src.STARTDATETIME,
                tgt.ENDDATETIME                 = src.ENDDATETIME,
                tgt.LLDETAILID1                 = src.LLDETAILID1,
                tgt.LLDETAILID2                 = src.LLDETAILID2,
                tgt.LLDETAILID3                 = src.LLDETAILID3,
                tgt.LLDETAILID4                 = src.LLDETAILID4,
                tgt.LLDETAILID5                 = src.LLDETAILID5,
                tgt.LLDETAILID6                 = src.LLDETAILID6,
                tgt.LLDETAILID7                 = src.LLDETAILID7,
                tgt.LLDETAILID8                 = src.LLDETAILID8,
                tgt.LLDETAILID9                 = src.LLDETAILID9,
                tgt.LLDETAILID10                = src.LLDETAILID10,
                tgt.LLDETAILID11                = src.LLDETAILID11,
                tgt.LLDETAILID12                = src.LLDETAILID12,
                tgt.LLDETAILID13                = src.LLDETAILID13,
                tgt.LLDETAILID14                = src.LLDETAILID14,
                tgt.LLDETAILID15                = src.LLDETAILID15,
                tgt.ISAUTOGENERATED             = src.ISAUTOGENERATED,
                tgt.MODIFIEDBY                  = src.MODIFIEDBY,
                tgt.MODIFIEDON                  = src.MODIFIEDON,
                tgt.ADVSCHEDULECAPACITYDETAILID = src.ADVSCHEDULECAPACITYDETAILID,
                tgt.NOTE                        = src.NOTE,
                tgt.STARTDATETIMEUTC            = src.STARTDATETIMEUTC,
                tgt.ENDDATETIMEUTC              = src.ENDDATETIMEUTC,
                tgt.CALENDAREVENTID             = src.CALENDAREVENTID,
                tgt.ISCALENDARSYNC              = src.ISCALENDARSYNC,
                tgt.SCHEDULEGENERATEDSOURCE     = src.SCHEDULEGENERATEDSOURCE,
                tgt.USERHASBEENNOTIFIED         = src.USERHASBEENNOTIFIED
            WHEN NOT MATCHED AND src.CHANGE_TYPE IN (2,4) THEN INSERT (
                DATABASEPHYSICALNAME, SCHEDULEID, USERID, PAYTYPEID,
                STARTDATETIME, ENDDATETIME,
                LLDETAILID1, LLDETAILID2, LLDETAILID3, LLDETAILID4, LLDETAILID5,
                LLDETAILID6, LLDETAILID7, LLDETAILID8, LLDETAILID9, LLDETAILID10,
                LLDETAILID11, LLDETAILID12, LLDETAILID13, LLDETAILID14, LLDETAILID15,
                ISAUTOGENERATED, MODIFIEDBY, MODIFIEDON, ADVSCHEDULECAPACITYDETAILID,
                NOTE, STARTDATETIMEUTC, ENDDATETIMEUTC, CALENDAREVENTID,
                ISCALENDARSYNC, SCHEDULEGENERATEDSOURCE, USERHASBEENNOTIFIED
            ) VALUES (
                src.DATABASEPHYSICALNAME, src.SCHEDULEID, src.USERID, src.PAYTYPEID,
                src.STARTDATETIME, src.ENDDATETIME,
                src.LLDETAILID1, src.LLDETAILID2, src.LLDETAILID3, src.LLDETAILID4, src.LLDETAILID5,
                src.LLDETAILID6, src.LLDETAILID7, src.LLDETAILID8, src.LLDETAILID9, src.LLDETAILID10,
                src.LLDETAILID11, src.LLDETAILID12, src.LLDETAILID13, src.LLDETAILID14, src.LLDETAILID15,
                src.ISAUTOGENERATED, src.MODIFIEDBY, src.MODIFIEDON, src.ADVSCHEDULECAPACITYDETAILID,
                src.NOTE, src.STARTDATETIMEUTC, src.ENDDATETIMEUTC, src.CALENDAREVENTID,
                src.ISCALENDARSYNC, src.SCHEDULEGENERATEDSOURCE, src.USERHASBEENNOTIFIED
            )
        `;
        var merge_result = snowflake.createStatement({sqlText: merge_sql}).execute();
        merge_result.next();
        total_inserts = merge_result.getColumnValue(1);
        total_updates = merge_result.getColumnValue(2);
        total_deletes = merge_result.getColumnValue(3);

        return "Delta applied: " + files_processed + " file(s) across " +
               batch_count + " batch(es) -- " +
               "Rows copied to staging: " + total_rows_copied + ", " +
               "Inserts: " + total_inserts + ", Updates: " + total_updates +
               ", Deletes: " + total_deletes + ".";
    } catch (err) {
        throw new Error("DELTA_LOAD_SCHEDULE failed: " + err.message);
    }
';


-- =============================================================================
-- DELTA_LOAD_TIMEOFFDATA
-- PK: DATABASEPHYSICALNAME + TIMEOFFDATAID
-- DATABASEPHYSICALNAME derived from path via REGEXP_SUBSTR on METADATA$FILENAME
-- =============================================================================
