USE DATABASE &{{SNOWFLAKE_DATABASE}};
USE SCHEMA   &{{SNOWFLAKE_SCHEMA}};

CREATE OR REPLACE TABLE STG_DELTA_USERINFOISSALARY (
    CHANGE_TYPE         NUMBER(38,0),
    LSN                 NUMBER(38,0),
    DATABASEPHYSICALNAME VARCHAR(16777216),
    USERINFOISSALARYID  NUMBER(38,0),
    USERID              NUMBER(38,0),
    ISSALARY            BOOLEAN,
    STARTDATETIME       TIMESTAMP_NTZ(9),
    ENDDATETIME         TIMESTAMP_NTZ(9),
    MODIFIEDBY          NUMBER(38,0),
    MODIFIEDON          TIMESTAMP_NTZ(9)
);


CREATE OR REPLACE TABLE STG_DELTA_TIMEOFFREQUESTDETAIL (
    CHANGE_TYPE                     NUMBER(38,0),
    LSN                             NUMBER(38,0),
    DATABASEPHYSICALNAME            VARCHAR(16777216),
    TIMEOFFREQUESTDETAILID          NUMBER(38,0),
    TIMEOFFREQUESTID                NUMBER(38,0),
    STARTDATETIME                   TIMESTAMP_NTZ(9),
    ENDDATETIME                     TIMESTAMP_NTZ(9),
    STATUSTYPE                      NUMBER(38,0),
    ISDELETED                       BOOLEAN,
    STATUSCHANGEDBY                 NUMBER(38,0),
    STATUSCHANGEDON                 TIMESTAMP_NTZ(9),
    MGRNOTES                        VARCHAR(500),
    TIMESLICEPREID                  NUMBER(38,0),
    AUTORESETQUALIFYBYHOURSWORKED   BOOLEAN,
    ISCALENDARSYNC                  BOOLEAN,
    CALENDAREVENTID                 VARCHAR(16777216)
);


CREATE OR REPLACE TABLE STG_DELTA_CUSTOMER (
    CHANGE_TYPE                     NUMBER(38,0),
    LSN                             NUMBER(38,0),
    CUSTOMERID                      NUMBER(38,0),
    CUSTOMERNAME                    VARCHAR(100),
    DATABASECREATIONDATE            TIMESTAMP_NTZ(9),
    CUSTOMERALIAS                   VARCHAR(50),
    CUSTOMERSTATUS                  NUMBER(38,0),
    BRANDID                         NUMBER(38,0),
    DATABASEPHYSICALNAME            VARCHAR(50),
    DATABASESERVER                  VARCHAR(50),
    SUPPORTEMAILADDRESS             VARCHAR(100),
    IVRALIAS                        NUMBER(38,0),
    ACTIVEEMPLOYEES                 NUMBER(38,0),
    EMAILSERVER                     VARCHAR(100),
    EMAILPORT                       NUMBER(38,0),
    EMAILSSLENABLED                 BOOLEAN,
    EMAILACCOUNT                    VARCHAR(100),
    EMAILUSERNAME                   VARCHAR(100),
    EMAILPASSWORD                   VARCHAR(255),
    EMAILDOMAIN                     VARCHAR(255),
    EMAILSETTINGSOVERRIDE           BOOLEAN,
    QUEUEDELAYUNTIL                 TIMESTAMP_NTZ(9),
    MODIFIEDBY                      NUMBER(38,0),
    MODIFIEDON                      TIMESTAMP_NTZ(9),
    WIRELESSENABLED                 BOOLEAN,
    FINGERPRINTENABLED              BOOLEAN,
    CUSTOMERIDEXTERNAL              VARCHAR(255),
    WSTRACEENABLED                  BOOLEAN,
    WSTIMESTARTED                   TIMESTAMP_NTZ(9),
    WSSTARTEDBY                     NUMBER(38,0),
    TELEPUNCHALIAS                  NUMBER(38,0),
    BISCLIENTID                     VARCHAR(50),
    CUSTOMERLASTACTIVATEDBY         NUMBER(38,0),
    CUSTOMERLASTACTIVATEDON         TIMESTAMP_NTZ(9),
    CUSTOMERLASTDEACTIVATEDBY       NUMBER(38,0),
    CUSTOMERLASTDEACTIVATEDON       TIMESTAMP_NTZ(9),
    ISPROXY                         BOOLEAN,
    MIGWORKFLOW                     NUMBER(38,0),
    ISESSENTIALS                    BOOLEAN,
    ISC2C                           BOOLEAN,
    DONOTDELETE                     BOOLEAN,
    ROLLUPMULTIFEINSHAREDEMPLOYEE   NUMBER(5,0),
    CUSTOMERCREATIONSTATUSTYPE      NUMBER(38,0),
    ENABLEAUTOCLOSINGTIMECARD       BOOLEAN,
    ENTERPRISECAIDBILL              VARCHAR(36),
    CEIDBILL                        VARCHAR(36),
    PAYROLLCLIENTIDBILL             VARCHAR(36),
    CLIENTTYPE                      NUMBER(38,0)
);


CREATE OR REPLACE TABLE STG_DELTA_ENTERPRISECUSTOMER (
    CHANGE_TYPE             NUMBER(38,0),
    LSN                     NUMBER(38,0),
    ENTERPRISECUSTOMERID    NUMBER(38,0),
    CUSTOMERID              NUMBER(38,0),
    PNGSSOCAID              VARCHAR(36),
    CEID                    VARCHAR(36),
    PAYROLLCLIENTID         VARCHAR(36),
    MODIFIEDBY              NUMBER(38,0),
    MODIFIEDON              TIMESTAMP_NTZ(9),
    STRATUSTIMECAID         VARCHAR(20),
    LEGALCLIENTNAME         VARCHAR(80),
    CEIDSTATUS              VARCHAR(10),
    CEIDSTATUSDATE          TIMESTAMP_NTZ(9),
    MODIFIEDCHANGEREASON    VARCHAR(100),
    CEIDSUPERSEDEDBY        VARCHAR(20),
    CACAID                  VARCHAR(20),
    HRISCAID                VARCHAR(20),
    BISCLIENTID             VARCHAR(50),
    USEDCLIENTMAINT         BOOLEAN
);


CREATE OR REPLACE TABLE STG_DELTA_PAYTYPE (
    CHANGE_TYPE             NUMBER(38,0),
    LSN                     NUMBER(38,0),
    DATABASEPHYSICALNAME    VARCHAR(16777216),
    ID                      NUMBER(38,0),
    PAYTYPEID               NUMBER(38,0),
    STARTDATETIME           TIMESTAMP_NTZ(9),
    ENDDATETIME             TIMESTAMP_NTZ(9),
    ISDELETED               BOOLEAN,
    PAYTYPENAME             VARCHAR(50),
    PAYTYPECODE             VARCHAR(50),
    COUNTTOWARDSHOLIDAYMIN  BOOLEAN,
    OVERRIDESABSENCE        BOOLEAN,
    ISWORKTYPE              BOOLEAN,
    APPLYTOOVERTIME         BOOLEAN,
    INCLUDEINBLENDEDRATE    BOOLEAN,
    APPLYTOTIMEOFF          BOOLEAN,
    CANBEOVERTIME           BOOLEAN,
    DEFAULTPAYLEVELRATETYPE NUMBER(38,0),
    ISOVERTIMETYPE          BOOLEAN,
    OVERTIMEFACTOR          NUMBER(18,2),
    COLORCODE               VARCHAR(1),
    MODIFIEDBY              NUMBER(38,0),
    MODIFIEDON              TIMESTAMP_NTZ(9),
    ALLOWSHIFTDIFF          BOOLEAN,
    DEDUCTFROMPAYTYPE       BOOLEAN,
    DEDUCTFROMPAYTYPEID     NUMBER(38,0),
    ISDURATIONONLY          BOOLEAN,
    ISLLREQUIRED            BOOLEAN,
    ISFMLATYPE              BOOLEAN,
    PAYATWEIGHTEDRATE       BOOLEAN
);


CREATE OR REPLACE TABLE STG_DELTA_SCHEDULE (
    CHANGE_TYPE                     NUMBER(38,0),
    LSN                             NUMBER(38,0),
    DATABASEPHYSICALNAME            VARCHAR(16777216),
    SCHEDULEID                      NUMBER(38,0),
    USERID                          NUMBER(38,0),
    PAYTYPEID                       NUMBER(38,0),
    STARTDATETIME                   TIMESTAMP_NTZ(9),
    ENDDATETIME                     TIMESTAMP_NTZ(9),
    LLDETAILID1                     NUMBER(38,0),
    LLDETAILID2                     NUMBER(38,0),
    LLDETAILID3                     NUMBER(38,0),
    LLDETAILID4                     NUMBER(38,0),
    LLDETAILID5                     NUMBER(38,0),
    LLDETAILID6                     NUMBER(38,0),
    LLDETAILID7                     NUMBER(38,0),
    LLDETAILID8                     NUMBER(38,0),
    LLDETAILID9                     NUMBER(38,0),
    LLDETAILID10                    NUMBER(38,0),
    LLDETAILID11                    NUMBER(38,0),
    LLDETAILID12                    NUMBER(38,0),
    LLDETAILID13                    NUMBER(38,0),
    LLDETAILID14                    NUMBER(38,0),
    LLDETAILID15                    NUMBER(38,0),
    ISAUTOGENERATED                 BOOLEAN,
    MODIFIEDBY                      NUMBER(38,0),
    MODIFIEDON                      TIMESTAMP_NTZ(9),
    ADVSCHEDULECAPACITYDETAILID     NUMBER(38,0),
    NOTE                            VARCHAR(16777216),
    STARTDATETIMEUTC                TIMESTAMP_NTZ(9),
    ENDDATETIMEUTC                  TIMESTAMP_NTZ(9),
    CALENDAREVENTID                 VARCHAR(16777216),
    ISCALENDARSYNC                  BOOLEAN,
    SCHEDULEGENERATEDSOURCE         NUMBER(38,0),
    USERHASBEENNOTIFIED             BOOLEAN
);


CREATE OR REPLACE TABLE STG_DELTA_TIMEOFFDATA (
    CHANGE_TYPE                 NUMBER(38,0),
    LSN                         NUMBER(38,0),
    DATABASEPHYSICALNAME        VARCHAR(16777216),
    TIMEOFFDATAID               NUMBER(38,0),
    USERID                      NUMBER(38,0),
    PAYTYPEID                   NUMBER(38,0),
    ACCRUEDSECS                 NUMBER(38,0),
    GRANTEDSECS                 NUMBER(38,0),
    MANSECS                     NUMBER(38,0),
    USEDSECS                    NUMBER(38,0),
    AVAILABLESECS               NUMBER(38,0),
    APPLYTODATETIME             TIMESTAMP_NTZ(9),
    ADJUSTMENTUSERID            NUMBER(38,0),
    ISSYSTEMGENERATED           BOOLEAN,
    NOTES                       VARCHAR(16777216),
    TIMESLICEPREID              NUMBER(38,0),
    CREATIONDATETIME            TIMESTAMP_NTZ(9),
    MODIFIEDBY                  NUMBER(38,0),
    MODIFIEDON                  TIMESTAMP_NTZ(9),
    MAKEUPSECS                  NUMBER(38,0),
    ANCHORPOINT                 BOOLEAN,
    ROLLOVERSECS                NUMBER(38,0),
    FORFEITEDSECS               NUMBER(38,0),
    TRANSFERINID                NUMBER(38,0),
    TRANSFERINSECS              NUMBER(38,0),
    TRANSFEROUTID               NUMBER(38,0),
    TRANSFEROUTSECS             NUMBER(38,0),
    TOTALACCRUEDSECS            NUMBER(38,0),
    MANTYPE                     NUMBER(38,0),
    ISROLLOVER                  BOOLEAN,
    PROCESSINDEX                NUMBER(38,0),
    DELAYEDGRANTSECS            NUMBER(38,0),
    SECONDSWORKEDSTORE          NUMBER(38,0),
    EXPIRESDATETIME             TIMESTAMP_NTZ(9),
    ROLLOVERTRANSFERINID        NUMBER(38,0),
    ROLLOVERTRANSFERINSECS      NUMBER(38,0),
    ROLLOVERTRANSFEROUTID       NUMBER(38,0),
    ROLLOVERTRANSFEROUTSECS     NUMBER(38,0),
    LASTPROCESSEDEVENTID        VARCHAR(16777216),
    LASTPROCESSEDEVENTDATETIME  TIMESTAMP_NTZ(9)
);


CREATE OR REPLACE TABLE STG_DELTA_TIMEOFFREQUEST (
    CHANGE_TYPE             NUMBER(38,0),
    LSN                     NUMBER(38,0),
    DATABASEPHYSICALNAME    VARCHAR(16777216),
    TIMEOFFREQUESTID        NUMBER(38,0),
    USERID                  NUMBER(38,0),
    PAYTYPEID               NUMBER(38,0),
    TIMEOFFPOLICYDETAILID   NUMBER(38,0),
    DATETIMESUBMITTED       TIMESTAMP_NTZ(9),
    STARTDATETIME           TIMESTAMP_NTZ(9),
    ENDDATETIME             TIMESTAMP_NTZ(9),
    INCLUDEWEEKENDS         BOOLEAN,
    DURATIONPERDAYSECS      NUMBER(38,0),
    STATUSTYPE              NUMBER(38,0),
    STATUSCHANGEDON         TIMESTAMP_NTZ(9),
    EMPNOTES                VARCHAR(500),
    ISBUYOUTREQUEST         BOOLEAN,
    BUYOUTSECS              NUMBER(38,0),
    BUYOUTADJUSTMENTID      NUMBER(38,0),
    PAYADJUSTMENTDATAID     NUMBER(38,0)
);


CREATE OR REPLACE TABLE STG_DELTA_TIMESLICEPOST (
    CHANGE_TYPE                 NUMBER(38,0),
    LSN                         NUMBER(38,0),
    DATABASEPHYSICALNAME        VARCHAR(16777216),
    TIMESLICEPOSTID             NUMBER(38,0),
    USERID                      NUMBER(38,0),
    PAYTYPEID                   NUMBER(38,0),
    TIMESLICEPREIDIN            NUMBER(38,0),
    TIMESLICEPREIDOUT           NUMBER(38,0),
    ACTUALDATETIMEIN            TIMESTAMP_NTZ(9),
    ACTUALDATETIMEOUT           TIMESTAMP_NTZ(9),
    ROUNDEDDATETIMEIN           TIMESTAMP_NTZ(9),
    ROUNDEDDATETIMEOUT          TIMESTAMP_NTZ(9),
    UTCDATETIMEIN               TIMESTAMP_NTZ(9),
    UTCDATETIMEOUT              TIMESTAMP_NTZ(9),
    TOTALPAIDDURATIONSECS       NUMBER(38,0),
    REGDURATIONSECS             NUMBER(38,0),
    OTDURATIONSECS              NUMBER(38,0),
    UNPAIDDURATIONSECS          NUMBER(38,0),
    MGRAPPROVEDIN               BOOLEAN,
    MGRAPPROVEDOUT              BOOLEAN,
    MGRNOTEIN                   VARCHAR(16777216),
    MGRNOTEOUT                  VARCHAR(16777216),
    EMPAPPROVEDIN               BOOLEAN,
    EMPAPPROVEDOUT              BOOLEAN,
    EMPNOTEIN                   VARCHAR(16777216),
    EMPNOTEOUT                  VARCHAR(16777216),
    TIMESHEETSUBMISSIONIN       BOOLEAN,
    TIMESHEETSUBMISSIONOUT      BOOLEAN,
    PAYRATE                     NUMBER(19,4),
    CHARGERATE                  NUMBER(19,4),
    TOTALEARNINGS               NUMBER(19,4),
    MISSINGPUNCHTYPEIN          NUMBER(38,0),
    MISSINGPUNCHTYPEOUT         NUMBER(38,0),
    ISMODIFIEDIN                BOOLEAN,
    ISMODIFIEDOUT               BOOLEAN,
    SCHEDULEID                  NUMBER(38,0),
    SCHEDULEDETAILID            NUMBER(38,0),
    APPLYTODATE                 TIMESTAMP_NTZ(9),
    CLOSEDTYPE                  NUMBER(38,0),
    TIMESLICEGROUPID            VARCHAR(50),
    LLDETAILID1                 NUMBER(38,0),
    LLDETAILID2                 NUMBER(38,0),
    LLDETAILID3                 NUMBER(38,0),
    LLDETAILID4                 NUMBER(38,0),
    LLDETAILID5                 NUMBER(38,0),
    LLDETAILID6                 NUMBER(38,0),
    LLDETAILID7                 NUMBER(38,0),
    LLDETAILID8                 NUMBER(38,0),
    LLDETAILID9                 NUMBER(38,0),
    LLDETAILID10                NUMBER(38,0),
    LLDETAILID11                NUMBER(38,0),
    LLDETAILID12                NUMBER(38,0),
    LLDETAILID13                NUMBER(38,0),
    LLDETAILID14                NUMBER(38,0),
    LLDETAILID15                NUMBER(38,0),
    HASHVALUE                   VARCHAR(900),
    TRANSACTIONTYPEIN           NUMBER(38,0),
    TRANSACTIONTYPEOUT          NUMBER(38,0),
    TRANSACTIONSOURCEIN         NUMBER(38,0),
    TRANSACTIONSOURCEOUT        NUMBER(38,0),
    APPLYTOOVERTIME             BOOLEAN,
    PAYLEVELRATETYPE            NUMBER(38,0),
    HASMODIFIER                 BOOLEAN,
    ISCANCELED                  BOOLEAN,
    COUNTTOWARDSHOLIDAYMIN      BOOLEAN,
    HASSHIFTDIFF                BOOLEAN,
    ISMEALPREMIUM               BOOLEAN,
    MODIFIEDBY                  NUMBER(38,0),
    MODIFIEDON                  TIMESTAMP_NTZ(9),
    ADMINAPPROVEDIN             BOOLEAN,
    ADMINAPPROVEDOUT            BOOLEAN,
    MGR2APPROVEDIN              BOOLEAN,
    MGR2APPROVEDOUT             BOOLEAN,
    LONGITUDEIN                 NUMBER(18,4),
    LONGITUDEOUT                NUMBER(18,4),
    LATITUDEIN                  NUMBER(18,4),
    LATITUDEOUT                 NUMBER(18,4),
    ISCOMPTIME                  BOOLEAN,
    COMPTIMEREQUESTID           NUMBER(38,0),
    COMPTIMEOTCONVERTEDSECS     NUMBER(38,0),
    MGRAPPROVEDBYIN             NUMBER(38,0),
    MGRAPPROVEDBYOUT            NUMBER(38,0),
    MGR2APPROVEDBYIN            NUMBER(38,0),
    MGR2APPROVEDBYOUT           NUMBER(38,0),
    ADMINAPPROVEDBYIN           NUMBER(38,0),
    ADMINAPPROVEDBYOUT          NUMBER(38,0),
    ISFORECAST                  BOOLEAN,
    ISRECONCILE                 BOOLEAN,
    ISSWIPEANDGOIN              BOOLEAN,
    ISSWIPEANDGOOUT             BOOLEAN,
    POPULATEDFROMSCHEDULEIN     BOOLEAN,
    POPULATEDFROMSCHEDULEOUT    BOOLEAN,
    ISCALLBACK                  BOOLEAN,
    ACCURACYIN                  NUMBER(18,4),
    ACCURACYOUT                 NUMBER(18,4),
    ISBREAKPREMIUM              BOOLEAN,
    ADDITIONALPREMIUMTYPE       NUMBER(38,0)
);


CREATE OR REPLACE TABLE STG_DELTA_TIMESLICEPOSTEXCEPTIONDETAIL (
    CHANGE_TYPE                     NUMBER(38,0),
    LSN                             NUMBER(38,0),
    DATABASEPHYSICALNAME            VARCHAR(16777216),
    TIMESLICEPOSTEXCEPTIONDETAILID  NUMBER(38,0),
    USERID                          NUMBER(38,0),
    TIMESLICEPOSTID                 NUMBER(38,0),
    TIMESLICEPREID                  NUMBER(38,0),
    SCHEDULEID                      NUMBER(38,0),
    DATETIME                        TIMESTAMP_NTZ(9),
    EXCEPTIONPOLICYRULEID           NUMBER(38,0),
    EXCEPTIONTYPE                   NUMBER(38,0),
    TRANSACTIONTYPE                 NUMBER(38,0),
    EXCEPTIONPARAMETERSECS          NUMBER(38,0),
    HASHVALUE                       VARCHAR(900),
    ISACKNOWLEDGED                  BOOLEAN,
    MODIFIEDBY                      NUMBER(38,0),
    MODIFIEDON                      TIMESTAMP_NTZ(9),
    MGRNOTE                         VARCHAR(16777216),
    ACKNOWLEDGEDBY                  NUMBER(38,0)
);


CREATE OR REPLACE TABLE STG_DELTA_TIMESLICEPOSTSHIFTDIFFDETAIL (
    CHANGE_TYPE                      NUMBER,
    LSN                              NUMBER(38,0),
    DATABASEPHYSICALNAME             VARCHAR,
    TIMESLICEPOSTSHIFTDIFFDETAILID   NUMBER,
    TIMESLICEPOSTID                  NUMBER,
    STARTDATETIME                    TIMESTAMP_NTZ,
    ENDDATETIME                      TIMESTAMP_NTZ,
    STARTDATETIMEUTC                 TIMESTAMP_NTZ,
    ENDDATETIMEUTC                   TIMESTAMP_NTZ,
    DURATION                         NUMBER,
    SHIFTDIFFDETAILID                NUMBER,
    SHIFTDIFFCODE                    VARCHAR(200),
    SHIFTDIFFFACTOR                  NUMBER(18,2),
    SHIFTDIFFADDITIONAL              NUMBER(19,4),
    FINALPAYRATE                     NUMBER(19,4),
    HASHVALUE                        VARCHAR(900),
    MODIFIEDBY                       NUMBER,
    MODIFIEDON                       TIMESTAMP_NTZ,
    SHIFTDIFFAFTEROVERTIME           BOOLEAN
);

-- =============================================================================
-- DELTA_LOAD_TIMESLICEPOSTSHIFTDIFFDETAIL
-- Processes delta CSV files for the TIMESLICEPOSTSHIFTDIFFDETAIL table.
-- table_id : bb67bf1f-a87a-1912-57fd-686aee5c7361
-- PK       : DATABASEPHYSICALNAME + TIMESLICEPOSTSHIFTDIFFDETAILID
-- change_type: 1=DELETE  2=INSERT  3=skip  4=UPDATE
-- =============================================================================

CREATE OR REPLACE TABLE STG_DELTA_USERINFO (
    CHANGE_TYPE          NUMBER,
    LSN                  NUMBER(38,0),
    DATABASEPHYSICALNAME VARCHAR,
    USERID               NUMBER,
    EMPIDENTIFIER        VARCHAR(50),
    MODIFIEDON           TIMESTAMP_NTZ,
    STARTDATE            TIMESTAMP_NTZ
);

-- =============================================================================
-- DELTA_LOAD_USERINFO
-- Processes delta CSV files for the USERINFO table.
-- table_id : c930ce7d-904e-31a5-156d-559bc63e4246
-- PK       : DATABASEPHYSICALNAME + USERID
-- change_type: 1=DELETE  2=INSERT  3=skip  4=UPDATE
-- CSV cols : $3=CHANGE_TYPE, path REGEXP=DATABASEPHYSICALNAME,
--            $5=USERID, $6=EMPIDENTIFIER, $44=MODIFIEDON, $52=STARTDATE
-- =============================================================================
