"""
TAA Pipeline Table Onboarding Tool
===================================
Generates deployment-ready SQL for adding a new table to both the full Parquet
load pipeline (onelake_taa_full_parquet_ingest.sql) and the delta CSV load
pipeline (onelake_taa_delta_csv_ingest.sql).

Usage:
    python table_onboarding_tool.py <config.json>
    python table_onboarding_tool.py <config.json> --output my_table.sql

Input:  A JSON config file describing the new table (see template).
Output: A .sql file containing all required objects, ready to review and deploy.

Generated objects (in deployment order):
    Full load:
        1. Target table DDL
        2. FULL_LOAD_<TABLE> procedure
        3. INSERT INTO INGEST_TAA_TABLE_CONFIG
        4. Wave task DDL  (TAA_FL_W1_<TABLE> or TAA_FL_W2_<TABLE>)
        5. ALTER TASK TAA_FL_FINALIZE ADD AFTER <new_task>
        6. ALTER TASK <new_task> RESUME

    Delta load:
        7.  STG_DELTA_<TABLE> staging table DDL
        8.  DELTA_LOAD_<TABLE> procedure
        9.  Wave task DDL  (TAA_DL_W1_<TABLE> or TAA_DL_W2_<TABLE>)
        10. ALTER TASK TAA_DL_FINALIZE ADD AFTER <new_task>
        11. ALTER TASK <new_task> RESUME

Author: Generated by GitHub Copilot
"""

import json
import sys
import os
import argparse
from datetime import date


# ---------------------------------------------------------------------------
# Snowflake type → Parquet COPY cast
# Used in FULL_LOAD_<TABLE> for the $1:ColName::TYPE expressions.
# ---------------------------------------------------------------------------
def parquet_cast(sf_type: str) -> str:
    t = sf_type.upper().strip()
    if t.startswith("VARCHAR") or t == "TEXT":
        return "::TEXT"
    if t.startswith("NUMBER") or t.startswith("NUMERIC") or t.startswith("DECIMAL"):
        return f"::{sf_type}"
    if t in ("BOOLEAN", "BOOL"):
        return "::BOOLEAN"
    if "TIMESTAMP_NTZ" in t:
        return "::TIMESTAMP_NTZ"
    if "TIMESTAMP_TZ" in t:
        return "::TIMESTAMP_TZ"
    if "TIMESTAMP_LTZ" in t:
        return "::TIMESTAMP_LTZ"
    if "TIMESTAMP" in t:
        return "::TIMESTAMP_NTZ"
    if t.startswith("FLOAT") or t.startswith("DOUBLE") or t == "REAL":
        return f"::{sf_type}"
    if t.startswith("DATE"):
        return "::DATE"
    if t.startswith("TIME"):
        return "::TIME"
    # Default: cast to the declared type
    return f"::{sf_type}"


# ---------------------------------------------------------------------------
# Snowflake type → CSV COPY cast (TRY_ wrappers for date/time types)
# Used in DELTA_LOAD_<TABLE> for the $N::TYPE positional expressions.
# ---------------------------------------------------------------------------
def csv_cast(sf_type: str) -> str:
    t = sf_type.upper().strip()
    if "TIMESTAMP" in t:
        return f"TRY_TO_TIMESTAMP_NTZ(${{pos}})"   # placeholder, filled in below
    if t.startswith("VARCHAR") or t == "TEXT":
        return "${{pos}}::TEXT"
    if t.startswith("NUMBER") or t.startswith("NUMERIC") or t.startswith("DECIMAL"):
        return f"${{pos}}::{sf_type}"
    if t in ("BOOLEAN", "BOOL"):
        return "${{pos}}::BOOLEAN"
    if t.startswith("FLOAT") or t.startswith("DOUBLE") or t == "REAL":
        return f"${{pos}}::{sf_type}"
    if t.startswith("DATE"):
        return "TRY_TO_DATE(${{pos}})"
    return f"${{pos}}::{sf_type}"


def csv_cast_expr(sf_type: str, pos: int) -> str:
    """Return the final CSV cast expression for a given column position."""
    t = sf_type.upper().strip()
    if "TIMESTAMP" in t:
        return f"TRY_TO_TIMESTAMP_NTZ(${pos})"
    if t.startswith("DATE"):
        return f"TRY_TO_DATE(${pos})"
    if t.startswith("VARCHAR") or t == "TEXT":
        return f"${pos}::TEXT"
    if t in ("BOOLEAN", "BOOL"):
        return f"${pos}::BOOLEAN"
    # NUMBER, FLOAT, etc.
    return f"${pos}::{sf_type}"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def indent(text: str, spaces: int = 4) -> str:
    pad = " " * spaces
    return "\n".join(pad + line for line in text.splitlines())


def section(title: str) -> str:
    bar = "=" * 77
    return f"""
-- {bar}
-- {title}
-- {bar}
"""


def subsection(title: str) -> str:
    bar = "-" * 77
    return f"""
-- {bar}
-- {title}
-- {bar}
"""


# ---------------------------------------------------------------------------
# 1. Target table DDL
# ---------------------------------------------------------------------------

def gen_target_table(cfg: dict) -> str:
    tname = cfg["table_name"].upper()
    lines = []
    for col in cfg["columns"]:
        name = col["name"].upper()
        sf_type = col["sf_type"]
        nullable = " NOT NULL" if col.get("not_null", True) else ""
        lines.append(f"    {name:<50} {sf_type}{nullable},")

    # Primary key constraint
    pk_cols = [c["name"].upper() for c in cfg["columns"] if c.get("pk")]
    if pk_cols:
        pk_list = ", ".join(pk_cols)
        lines.append(f"    CONSTRAINT PK_{tname} PRIMARY KEY ({pk_list})")
    else:
        # Remove trailing comma from last column line
        if lines:
            lines[-1] = lines[-1].rstrip(",")

    col_block = "\n".join(lines)
    return f"""CREATE OR REPLACE TABLE {tname} (
{col_block}
);
"""


# ---------------------------------------------------------------------------
# 2. FULL_LOAD_<TABLE> procedure
# ---------------------------------------------------------------------------

def gen_full_load_proc(cfg: dict) -> str:
    tname  = cfg["table_name"].upper()
    tid    = cfg["table_uuid"]
    mt     = cfg.get("is_multi_tenant", True)

    # Build column list for COPY INTO target
    copy_cols = []
    select_exprs = []
    for col in cfg["columns"]:
        cname = col["name"].upper()
        copy_cols.append(f"                    {cname}")
        if mt and cname == "DATABASEPHYSICALNAME":
            # Derived from file path, not Parquet payload
            select_exprs.append(
                "                    REGEXP_SUBSTR(METADATA$FILENAME::STRING,"
                " ''/([^/]+)/Tables/'', 1, 1, ''e'')"
            )
        else:
            cast = parquet_cast(col["sf_type"])
            select_exprs.append(f"                    $1:{col['name']}{cast}")

    copy_col_block   = ",\n".join(copy_cols)
    select_expr_block = ",\n".join(select_exprs)

    return f"""{subsection(f"PROCEDURE: FULL_LOAD_{tname}")}
CREATE OR REPLACE PROCEDURE FULL_LOAD_{tname}(
    STAGE_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var total_rows_loaded     = 0;
    var files_processed       = 0;
    var total_files_identified = 0;

    try {{
        var get_files_query = `
            SELECT
                SUBSTRING(full_file_path, POSITION(''\\'/LandingZone/\\'' IN full_file_path)) AS relative_path,
                client_id,
                table_id,
                filename,
                full_file_path
            FROM STAGE_TAA_FULL_FILE_MANIFEST
            WHERE table_id = ''{tid}''
            ORDER BY client_id, table_id
        `;

        var file_results  = snowflake.createStatement({{sqlText: get_files_query}}).execute();
        var file_list     = [];
        var file_metadata = {{}};

        while (file_results.next()) {{
            var relative_path  = file_results.getColumnValue(1);
            var client_id      = file_results.getColumnValue(2);
            var table_id       = file_results.getColumnValue(3);
            var filename       = file_results.getColumnValue(4);
            var full_file_path = file_results.getColumnValue(5);

            file_list.push("''" + relative_path + "''");
            file_metadata[relative_path] = {{
                client_id:      client_id,
                table_id:       table_id,
                filename:       filename,
                full_file_path: full_file_path
            }};
        }}

        total_files_identified = file_list.length;
        if (total_files_identified === 0) {{
            return "No files found to load for {tname}.";
        }}

        var batch_size  = 1000;
        var batch_count = Math.ceil(file_list.length / batch_size);

        for (var batch_num = 0; batch_num < batch_count; batch_num++) {{
            var start        = batch_num * batch_size;
            var end          = Math.min(start + batch_size, file_list.length);
            var batch_files  = file_list.slice(start, end);
            var files_clause = batch_files.join(", ");

            var copy_command = `
                COPY INTO {tname} (
{copy_col_block}
                )
                FROM (
                    SELECT
{select_expr_block}
                    FROM @` + STAGE_NAME + `
                    (FILE_FORMAT => ''FF_TAA_ONELAKE_PARQUET'')
                )
                FILE_FORMAT = (TYPE = PARQUET)
                FILES = (` + files_clause + `)
                ON_ERROR = CONTINUE
                FORCE = TRUE
            `;

            var copy_result = snowflake.createStatement({{sqlText: copy_command}}).execute();

            while (copy_result.next()) {{
                var file_name   = copy_result.getColumnValue(1);
                var status      = copy_result.getColumnValue(2);
                var rows_loaded = copy_result.getColumnValue(4);
                var first_error = copy_result.getColumnValue(7);

                var relative_path = file_name.indexOf("/LandingZone/") > -1
                    ? file_name.substring(file_name.indexOf("/LandingZone/"))
                    : file_name;

                var metadata    = file_metadata[relative_path] || {{}};
                var load_status = (status === "LOADED") ? "SUCCESS" : "FAILED";

                var safe_filename  = (metadata.filename       || file_name).replace(/''/g, "''''");
                var safe_client_id = (metadata.client_id      || "UNKNOWN");
                var safe_table_id  = (metadata.table_id       || "UNKNOWN");
                var safe_full_path = (metadata.full_file_path || file_name).replace(/''/g, "''''");
                var safe_error     = first_error ? first_error.replace(/''/g, "''''") : null;

                snowflake.createStatement({{ sqlText: `
                    INSERT INTO INGEST_TAA_FILE_AUDIT
                        (file_name, client_id, table_id, rows_loaded, batch_number,
                         load_status, error_message, full_stage_path)
                    VALUES (
                        ''` + safe_filename  + `'',
                        ''` + safe_client_id + `'',
                        ''` + safe_table_id  + `'',
                        `  + rows_loaded     + `,
                        `  + (batch_num + 1) + `,
                        ''` + load_status    + `'',
                        `  + (safe_error ? "''" + safe_error + "''" : "NULL") + `,
                        ''` + safe_full_path + `''
                    )
                `}}).execute();

                total_rows_loaded += rows_loaded;
                files_processed++;
            }}
        }}

        return "Load complete. Processed " + batch_count + " batch(es). " +
               "Files: " + files_processed + " / " + total_files_identified + ". " +
               "Rows loaded: " + total_rows_loaded;

    }} catch (err) {{
        throw new Error("FULL_LOAD_{tname} failed: " + err.message);
    }}
';
"""


# ---------------------------------------------------------------------------
# 3. INGEST_TAA_TABLE_CONFIG INSERT
# ---------------------------------------------------------------------------

def gen_config_insert(cfg: dict) -> str:
    tname       = cfg["table_name"].upper()
    tid         = cfg["table_uuid"]
    load_order  = cfg.get("load_order", 10)
    description = cfg.get("description", "").replace("'", "''")
    mt          = str(cfg.get("is_multi_tenant", True)).upper()
    active_fl   = str(cfg.get("is_active_full_load", True)).upper()
    active_dl   = str(cfg.get("is_active_delta_load", True)).upper()

    return f"""
-- Register the new table in the pipeline config
INSERT INTO INGEST_TAA_TABLE_CONFIG
    (TABLE_NAME, LOAD_PROCEDURE_NAME, DELTA_LOAD_PROCEDURE_NAME, SOURCE_TABLE_ID,
     LOAD_ORDER, IS_ACTIVE_FULL_LOAD, IS_ACTIVE_DELTA_LOAD, IS_MULTI_TENANT, DESCRIPTION)
VALUES (
    '{tname}',
    'FULL_LOAD_{tname}()',
    'DELTA_LOAD_{tname}()',
    '{tid}',
    {load_order},
    {active_fl},
    {active_dl},
    {mt},
    '{description}'
);
"""


# ---------------------------------------------------------------------------
# 4 & 9. Task DDL (full load and delta)
# ---------------------------------------------------------------------------

def gen_task_ddl(cfg: dict, pipeline: str) -> str:
    """
    pipeline = 'FL' (full load) or 'DL' (delta load)
    """
    tname      = cfg["table_name"].upper()
    wave       = cfg.get("wave", 1)
    parent_tbl = cfg.get("wave2_parent", "").upper() if wave == 2 else None
    wh         = cfg.get("warehouse", "WH_DS_AUTOMATION_TST")

    prefix     = f"TAA_{pipeline}"
    wave_label = f"W{wave}"
    task_name  = f"{prefix}_{wave_label}_{tname}"
    dispatcher = "FULL_LOAD_FROM_CONFIG" if pipeline == "FL" else "DELTA_LOAD_FROM_CONFIG"

    if wave == 1:
        after_clause = f"AFTER {prefix}_ROOT"
    else:
        after_clause = f"AFTER {prefix}_W1_{parent_tbl}"

    pipe_label = "full load" if pipeline == "FL" else "delta load"
    return f"""
CREATE OR REPLACE TASK {task_name}
    WAREHOUSE = {wh}
    COMMENT   = 'TAA {pipe_label} Wave {wave}: loads {tname}.'
    {after_clause}
AS
CALL {dispatcher}('{tname}');
"""


# ---------------------------------------------------------------------------
# 5 & 10. Add the new task to the FINALIZE task's AFTER list
# ---------------------------------------------------------------------------

def gen_finalize_alter(cfg: dict, pipeline: str) -> str:
    tname      = cfg["table_name"].upper()
    wave       = cfg.get("wave", 1)
    prefix     = f"TAA_{pipeline}"
    wave_label = f"W{wave}"
    task_name  = f"{prefix}_{wave_label}_{tname}"
    wh         = cfg.get("warehouse", "WH_DS_AUTOMATION_TST")
    finalize   = f"{prefix}_FINALIZE"

    pipe_label = "full load" if pipeline == "FL" else "delta load"
    return f"""
-- Add the new task as a dependency of the finalize task.
-- TAA_FL/DL_ROOT must be SUSPENDED before altering DAG dependencies.
ALTER TASK {prefix}_ROOT SUSPEND;
ALTER TASK {finalize} ADD AFTER {task_name};
ALTER TASK {task_name} RESUME;
ALTER TASK {prefix}_ROOT RESUME;
"""


# ---------------------------------------------------------------------------
# 7. STG_DELTA_<TABLE> staging table
# ---------------------------------------------------------------------------

def gen_stg_delta_table(cfg: dict) -> str:
    tname = cfg["table_name"].upper()
    mt    = cfg.get("is_multi_tenant", True)

    lines = []
    # CHANGE_TYPE and LSN always first
    lines.append("    CHANGE_TYPE             NUMBER(38,0),")
    lines.append("    LSN                     NUMBER(38,0),")

    for col in cfg["columns"]:
        cname   = col["name"].upper()
        sf_type = col["sf_type"]
        if mt and cname == "DATABASEPHYSICALNAME":
            lines.append(f"    {cname:<40} {sf_type},")
            continue
        lines.append(f"    {cname:<40} {sf_type},")

    # Remove trailing comma from last line
    if lines:
        lines[-1] = lines[-1].rstrip(",")

    col_block = "\n".join(lines)
    return f"""
CREATE OR REPLACE TABLE STG_DELTA_{tname} (
{col_block}
);
"""


# ---------------------------------------------------------------------------
# 8. DELTA_LOAD_<TABLE> procedure
# ---------------------------------------------------------------------------

def gen_delta_load_proc(cfg: dict) -> str:
    tname  = cfg["table_name"].upper()
    tid    = cfg["table_uuid"]
    mt     = cfg.get("is_multi_tenant", True)

    # Build STG column list, COPY INTO select expressions, MERGE ON clause,
    # UPDATE SET clause, and INSERT column/values lists.

    # CSV column positions:
    # $1=hex_lsn_meta, $2=meta, $3=CHANGE_TYPE, $4=meta, $5+ = data columns
    # For multi-tenant tables DATABASEPHYSICALNAME comes from METADATA$FILENAME,
    # so it does NOT occupy a CSV positional slot.
    # For non-multi-tenant tables ALL columns are positional starting at $5.

    stg_cols   = ["CHANGE_TYPE", "LSN"]
    copy_cols  = ["CHANGE_TYPE", "LSN"]
    copy_exprs = [
        "                        $3::NUMBER(38,0)",
        "                        TO_NUMBER(SUBSTR($1::TEXT, 3), ''XXXXXXXXXXXXXXXXXXXXXXXX'')",
    ]

    if mt:
        stg_cols.append("DATABASEPHYSICALNAME")
        copy_cols.append("DATABASEPHYSICALNAME")
        copy_exprs.append(
            "                        REGEXP_SUBSTR(METADATA$FILENAME::STRING,"
            " ''/([^/]+)/Tables/'', 1, 1, ''e'')"
        )

    # Data columns start at CSV position 5
    csv_pos = 5
    for col in cfg["columns"]:
        cname = col["name"].upper()
        if mt and cname == "DATABASEPHYSICALNAME":
            continue  # already handled above
        stg_cols.append(cname)
        copy_cols.append(cname)
        copy_exprs.append(
            "                        " + csv_cast_expr(col["sf_type"], csv_pos)
        )
        csv_pos += 1

    # MERGE: build ON clause from PK columns
    pk_cols     = [c["name"].upper() for c in cfg["columns"] if c.get("pk")]
    if mt and "DATABASEPHYSICALNAME" not in pk_cols:
        pk_cols = ["DATABASEPHYSICALNAME"] + pk_cols

    on_parts    = [f"tgt.{c} = src.{c}" for c in pk_cols]
    on_clause   = "\n            AND ".join(on_parts)

    # UPDATE SET: non-PK data columns (exclude DATABASEPHYSICALNAME and PK cols)
    update_cols = [
        c["name"].upper() for c in cfg["columns"]
        if not c.get("pk") and c["name"].upper() != "DATABASEPHYSICALNAME"
    ]
    update_parts = [f"tgt.{c} = src.{c}" for c in update_cols]
    update_block = ",\n                ".join(update_parts)

    # INSERT col list and values
    insert_cols = [c["name"].upper() for c in cfg["columns"]]
    if mt and "DATABASEPHYSICALNAME" not in insert_cols:
        insert_cols = ["DATABASEPHYSICALNAME"] + insert_cols
    # STG has CHANGE_TYPE, LSN, DATABASEPHYSICALNAME, then data cols
    # We only insert the actual target table columns (no CHANGE_TYPE/LSN)
    insert_col_list = ", ".join(insert_cols)
    insert_val_list = ", ".join(f"src.{c}" for c in insert_cols)

    qualify_pk = ", ".join(pk_cols)

    copy_col_block  = ",\n".join(f"                    {c}" for c in copy_cols)
    copy_expr_block = ",\n".join(copy_exprs)

    return f"""{subsection(f"PROCEDURE: DELTA_LOAD_{tname}")}
CREATE OR REPLACE PROCEDURE DELTA_LOAD_{tname}(
    STAGE_NAME VARCHAR
)
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS '
    var total_inserts     = 0;
    var total_updates     = 0;
    var total_deletes     = 0;
    var files_processed   = 0;
    var total_rows_copied = 0;

    try {{
        // Step 1: Collect all delta files for this table from the manifest.
        var get_files_query = `
            SELECT
                SUBSTRING(full_file_path, POSITION(''\\'/LandingZone/\\'' IN full_file_path)) AS relative_path,
                client_id,
                table_id,
                filename,
                full_file_path,
                last_modified
            FROM STAGE_TAA_DELTA_MANIFEST
            WHERE table_id = ''{tid}''
            ORDER BY last_modified ASC
        `;

        var file_results  = snowflake.createStatement({{sqlText: get_files_query}}).execute();
        var file_list     = [];
        var file_metadata = {{}};

        while (file_results.next()) {{
            var relative_path  = file_results.getColumnValue(1);
            var client_id      = file_results.getColumnValue(2);
            var table_id       = file_results.getColumnValue(3);
            var filename       = file_results.getColumnValue(4);
            var full_file_path = file_results.getColumnValue(5);

            file_list.push("''" + relative_path + "''");
            file_metadata[relative_path] = {{
                client_id:      client_id,
                table_id:       table_id,
                filename:       filename,
                full_file_path: full_file_path
            }};
        }}

        if (file_list.length === 0) {{
            return "No delta files found for {tname}.";
        }}

        // Step 2: Truncate staging once -- all batches append into it.
        snowflake.createStatement({{sqlText: "TRUNCATE TABLE STG_DELTA_{tname};"}}).execute();

        // Step 3: COPY all files into staging in batches of 1000.
        var batch_size  = 1000;
        var batch_count = Math.ceil(file_list.length / batch_size);

        for (var batch_num = 0; batch_num < batch_count; batch_num++) {{
            var start        = batch_num * batch_size;
            var end          = Math.min(start + batch_size, file_list.length);
            var batch_files  = file_list.slice(start, end);
            var files_clause = batch_files.join(", ");

            var copy_sql = `
                COPY INTO STG_DELTA_{tname} (
{copy_col_block}
                )
                FROM (
                    SELECT
{copy_expr_block}
                    FROM @` + STAGE_NAME + `
                    (FILE_FORMAT => ''FF_TAA_ONELAKE_CSV'')
                )
                FILES = (` + files_clause + `)
                ON_ERROR = ABORT_STATEMENT
                FORCE = TRUE
            `;
            var copy_result = snowflake.createStatement({{sqlText: copy_sql}}).execute();

            while (copy_result.next()) {{
                var file_name   = copy_result.getColumnValue(1);
                var status      = copy_result.getColumnValue(2);
                var rows_loaded = copy_result.getColumnValue(4);
                var first_error = copy_result.getColumnValue(7);

                var rel_path = file_name.indexOf("/LandingZone/") > -1
                    ? file_name.substring(file_name.indexOf("/LandingZone/"))
                    : file_name;

                var meta        = file_metadata[rel_path] || {{}};
                var load_status = (status === "LOADED") ? "SUCCESS" : "FAILED";

                var safe_filename  = (meta.filename       || file_name).replace(/''/g, "''''");
                var safe_full_path = (meta.full_file_path || file_name).replace(/''/g, "''''");
                var safe_client_id = (meta.client_id      || "UNKNOWN");
                var safe_table_id  = (meta.table_id       || "UNKNOWN");
                var safe_error     = first_error ? first_error.replace(/''/g, "''''") : null;

                snowflake.createStatement({{ sqlText: `
                    INSERT INTO INGEST_TAA_FILE_AUDIT
                        (file_name, client_id, table_id, rows_loaded, batch_number,
                         load_status, error_message, full_stage_path)
                    VALUES (
                        ''` + safe_filename  + `'',
                        ''` + safe_client_id + `'',
                        ''` + safe_table_id  + `'',
                        `  + rows_loaded     + `,
                        `  + (batch_num + 1) + `,
                        ''` + load_status    + `'',
                        `  + (safe_error ? "''" + safe_error + "''" : "NULL") + `,
                        ''` + safe_full_path + `''
                    )
                `}}).execute();

                total_rows_copied += rows_loaded;
                files_processed++;
            }}
        }}

        // Step 4: Single MERGE across all staged rows.
        // QUALIFY deduplicates by PK on LSN DESC -- last change wins.
        // change_type: 1=DELETE  2=INSERT  3=skip (old values row)  4=UPDATE
        var merge_sql = `
            MERGE INTO {tname} tgt
            USING (
                SELECT * FROM STG_DELTA_{tname}
                WHERE CHANGE_TYPE IN (1, 2, 4)
                QUALIFY ROW_NUMBER() OVER (
                    PARTITION BY {qualify_pk}
                    ORDER BY LSN DESC NULLS LAST
                ) = 1
            ) src
            ON  {on_clause}
            WHEN MATCHED AND src.CHANGE_TYPE = 1 THEN DELETE
            WHEN MATCHED AND src.CHANGE_TYPE IN (2, 4) THEN UPDATE SET
                {update_block}
            WHEN NOT MATCHED AND src.CHANGE_TYPE IN (2, 4) THEN INSERT (
                {insert_col_list}
            ) VALUES (
                {insert_val_list}
            )
        `;
        var merge_result = snowflake.createStatement({{sqlText: merge_sql}}).execute();
        merge_result.next();
        total_inserts = merge_result.getColumnValue(1);
        total_updates = merge_result.getColumnValue(2);
        total_deletes = merge_result.getColumnValue(3);

        return "Delta applied: " + files_processed + " file(s) across " + batch_count + " batch(es). " +
               "Staged rows: " + total_rows_copied + ". " +
               "Inserts: " + total_inserts + "  Updates: " + total_updates + "  Deletes: " + total_deletes;

    }} catch (err) {{
        throw new Error("DELTA_LOAD_{tname} failed: " + err.message);
    }}
';
"""


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------

def generate(cfg: dict) -> str:
    tname = cfg["table_name"].upper()
    today = date.today().isoformat()

    parts = []

    header = f"""-- =============================================================================
-- TAA Pipeline: New Table Onboarding -- {tname}
-- Generated:    {today}
-- Source UUID:  {cfg['table_uuid']}
-- Wave:         {cfg.get('wave', 1)}{f"  (parent: {cfg.get('wave2_parent','').upper()})" if cfg.get('wave', 1) == 2 else ""}
-- Multi-tenant: {cfg.get('is_multi_tenant', True)}
-- =============================================================================
--
-- DEPLOYMENT CHECKLIST:
--   1. Review all generated DDL and procedure bodies before executing.
--   2. Verify table_uuid matches the actual TABLE_ID in OneLake file paths.
--   3. Verify CSV column positions in DELTA_LOAD_{tname} match the actual
--      ChangeData file format (run a LIST + COPY sample if unsure).
--   4. Run the FULL LOAD section first; verify rows load correctly.
--   5. Run the DELTA LOAD section; verify STG table and MERGE work.
--   6. The ALTER TASK statements suspend+resume the DAG root -- run them
--      during a maintenance window or when no load is in progress.
--
-- AFTER DEPLOYMENT:
--   - Trigger a full load to populate INGEST_TAA_FULL_LOAD_STATE for {tname}.
--   - Delta loads for this table will then be eligible on the next run.
-- =============================================================================

use database onelake_test;
use schema kyle;
"""
    parts.append(header)

    # ---- Full load section ----
    parts.append(section(f"FULL LOAD -- {tname}"))
    parts.append(gen_target_table(cfg))
    parts.append(gen_full_load_proc(cfg))
    parts.append(gen_config_insert(cfg))
    parts.append(subsection(f"Task DAG -- Full Load Wave {cfg.get('wave',1)}: {tname}"))
    parts.append(gen_task_ddl(cfg, "FL"))
    parts.append(gen_finalize_alter(cfg, "FL"))

    # ---- Delta load section ----
    parts.append(section(f"DELTA LOAD -- {tname}"))
    parts.append(gen_stg_delta_table(cfg))
    parts.append(gen_delta_load_proc(cfg))
    parts.append(subsection(f"Task DAG -- Delta Load Wave {cfg.get('wave',1)}: {tname}"))
    parts.append(gen_task_ddl(cfg, "DL"))
    parts.append(gen_finalize_alter(cfg, "DL"))

    footer = f"""
-- =============================================================================
-- END OF GENERATED SCRIPT -- {tname}
-- =============================================================================
"""
    parts.append(footer)
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate TAA pipeline onboarding SQL for a new table."
    )
    parser.add_argument("config", help="Path to the table config JSON file.")
    parser.add_argument(
        "--output", "-o",
        help="Output .sql file path. Defaults to onboard_<TABLE_NAME>.sql in the same directory as the config."
    )
    args = parser.parse_args()

    config_path = args.config
    if not os.path.exists(config_path):
        print(f"ERROR: Config file not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    with open(config_path, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    # Basic validation
    required = ["table_name", "table_uuid", "columns"]
    for field in required:
        if field not in cfg:
            print(f"ERROR: Missing required config field: '{field}'", file=sys.stderr)
            sys.exit(1)

    if not cfg["columns"]:
        print("ERROR: 'columns' list is empty.", file=sys.stderr)
        sys.exit(1)

    pk_cols = [c for c in cfg["columns"] if c.get("pk")]
    if not pk_cols:
        print("WARNING: No columns marked as pk=true. MERGE ON clause will be empty.", file=sys.stderr)

    sql = generate(cfg)

    if args.output:
        out_path = args.output
    else:
        config_dir = os.path.dirname(os.path.abspath(config_path))
        out_path   = os.path.join(config_dir, f"onboard_{cfg['table_name'].upper()}.sql")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(sql)

    print(f"Generated: {out_path}")
    print(f"  Table:   {cfg['table_name'].upper()}")
    print(f"  UUID:    {cfg['table_uuid']}")
    print(f"  Columns: {len(cfg['columns'])}")
    print(f"  Wave:    {cfg.get('wave', 1)}")
    print(f"  Multi-tenant: {cfg.get('is_multi_tenant', True)}")


if __name__ == "__main__":
    main()
